(()=>{
  'use strict';
  const UI_SELECTOR='#lceoLeftRail,#lceoActionRail,#lceoActionDrawer,#lceoActionBackdrop,#lceoNavToast';
  const AREA_ORDER=['home','plan','work','money','content','growth','notes'];
  const svg={
    home:'<svg viewBox="0 0 24 24"><path d="M3 11.5 12 4l9 7.5"/><path d="M5.5 10.5V20h13v-9.5"/><path d="M9.5 20v-6h5v6"/></svg>',
    plan:'<svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4M17 3v4M3 10h18"/><path d="M7 14h3M14 14h3M7 18h3"/></svg>',
    work:'<svg viewBox="0 0 24 24"><rect x="3" y="7" width="18" height="13" rx="2"/><path d="M9 7V4h6v3M3 12h18M10 12v2h4v-2"/></svg>',
    money:'<svg viewBox="0 0 24 24"><path d="M12 2v20M17 6.5c0-1.7-2-3-5-3s-5 1.3-5 3 1.6 2.7 5 3.5 5 1.8 5 4-2.2 3.5-5 3.5-5-1.4-5-3.5"/></svg>',
    content:'<svg viewBox="0 0 24 24"><path d="m12 3 1.5 4.5L18 9l-4.5 1.5L12 15l-1.5-4.5L6 9l4.5-1.5L12 3Z"/><path d="m19 14 .8 2.2L22 17l-2.2.8L19 20l-.8-2.2L16 17l2.2-.8L19 14Z"/><path d="M5 15.5 6 18l2.5 1L6 20l-1 2.5L4 20l-2.5-1L4 18l1-2.5Z"/></svg>',
    growth:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1.5"/><path d="m16 8 5-5M17 3h4v4"/></svg>',
    notes:'<svg viewBox="0 0 24 24"><path d="M5 3h11l3 3v15H5z"/><path d="M16 3v4h4M8 11h8M8 15h8M8 19h5"/></svg>',
    plus:'<svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>',
    event:'<svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4M17 3v4M3 10h18M8 14h4v4H8z"/></svg>',
    task:'<svg viewBox="0 0 24 24"><rect x="4" y="4" width="16" height="16" rx="3"/><path d="m8 12 2.5 2.5L16 9"/></svg>',
    income:'<svg viewBox="0 0 24 24"><path d="M12 3v14M7 12l5 5 5-5"/><path d="M5 21h14"/></svg>',
    expense:'<svg viewBox="0 0 24 24"><path d="M12 21V7M7 12l5-5 5 5"/><path d="M5 3h14"/></svg>',
    note:'<svg viewBox="0 0 24 24"><path d="M4 20h4l11-11-4-4L4 16v4Z"/><path d="m13.5 6.5 4 4"/></svg>',
    calendar:'<svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4M17 3v4M3 10h18"/></svg>',
    week:'<svg viewBox="0 0 24 24"><path d="M4 5h16v14H4zM4 9h16M9 9v10M15 9v10"/></svg>',
    month:'<svg viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="17" rx="2"/><path d="M3 9h18M8 9v12M13 9v12M18 9v12M3 13h18M3 17h18"/></svg>',
    repeat:'<svg viewBox="0 0 24 24"><path d="M17 2l4 4-4 4"/><path d="M3 11V9a3 3 0 0 1 3-3h15"/><path d="m7 22-4-4 4-4"/><path d="M21 13v2a3 3 0 0 1-3 3H3"/></svg>',
    list:'<svg viewBox="0 0 24 24"><path d="M9 6h11M9 12h11M9 18h11"/><circle cx="4.5" cy="6" r="1"/><circle cx="4.5" cy="12" r="1"/><circle cx="4.5" cy="18" r="1"/></svg>',
    project:'<svg viewBox="0 0 24 24"><path d="M3 6h7l2 2h9v11H3z"/><path d="M8 13h8M8 16h5"/></svg>',
    client:'<svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="4"/><path d="M2.5 21a6.5 6.5 0 0 1 13 0"/><circle cx="18" cy="9" r="3"/><path d="M16 15.5a5 5 0 0 1 5.5 5"/></svg>',
    quote:'<svg viewBox="0 0 24 24"><path d="M6 4h12v16H6z"/><path d="M9 8h6M9 12h6M9 16h3"/></svg>',
    chart:'<svg viewBox="0 0 24 24"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></svg>',
    ledger:'<svg viewBox="0 0 24 24"><path d="M5 3h14v18H5zM9 3v18M12 8h4M12 12h4M12 16h4"/></svg>',
    idea:'<svg viewBox="0 0 24 24"><path d="M9 18h6M10 22h4"/><path d="M8 14c-1.4-1.1-2.5-3-2.5-5A6.5 6.5 0 0 1 18.5 9c0 2-1 3.9-2.5 5-1 .7-1 1.5-1 2H9c0-.5 0-1.3-1-2Z"/></svg>',
    goal:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="m8 12 2.5 2.5L16 9"/></svg>',
    habit:'<svg viewBox="0 0 24 24"><path d="M12 22c5-3 8-7.5 8-13V4l-8-2-8 2v5c0 5.5 3 10 8 13Z"/><path d="m8.5 12 2 2 5-5"/></svg>',
    reset:'<svg viewBox="0 0 24 24"><path d="M4 4v6h6"/><path d="M5.5 16a8 8 0 1 0 1-9.5L4 10"/></svg>',
    collapse:'<svg viewBox="0 0 24 24"><path d="m14 6-6 6 6 6"/></svg>',
    expand:'<svg viewBox="0 0 24 24"><path d="m10 6 6 6-6 6"/></svg>',
    menu:'<svg viewBox="0 0 24 24"><path d="M4 7h16M4 12h16M4 17h16"/></svg>'
  };
  const areas={
    home:{label:'Home',icon:'home',aliases:['home','dashboard'],actions:[['Add event','event','Schedule a time block or appointment.','quick',['Add event','New event','Agenda event']],['Add task','task','Capture the next action without leaving Home.','quick',['Add task','New task']],['Add income','income','Record expected or received income.','quick',['Add income','New income']],['Add expense','expense','Record a bill, purchase or outgoing payment.','quick',['Add expense','New expense']],['New content','content','Plan a social post or content idea.','quick',['New content','Add content','Social content']],['Quick note','note','Capture a journal entry or loose thought.','quick',['Quick note','New note','Add note','Journal entry']]]},
    plan:{label:'Plan',icon:'plan',aliases:['plan','planning'],actions:[['Day','event','Open the agenda-style Daily Planner.','tab',['Day','Daily']],['Week','week','Review the complete week and its priorities.','tab',['Week','Weekly']],['Month','month','See appointments, tasks and content together.','tab',['Month','Monthly']],['Routines','repeat','Apply or edit repeatable planning routines.','tab',['Routines','Routine']],['Add event','event','Add a scheduled event to your agenda.','quick',['Add event','New event','Agenda event']],['Add task','task','Add a flexible task to the planner.','quick',['Add task','New task']]]},
    work:{label:'Work',icon:'work',aliases:['work','business'],actions:[['Tasks','task','Open the working task list.','tab',['Tasks','Task inbox']],['Projects','project','Review active projects and next actions.','tab',['Projects','Project board']],['Clients','client','Open client and business records.','tab',['Clients','Client records']],['Quotes','quote','Review estimates, quotes and follow-ups.','tab',['Quotes','Estimates']],['New task','task','Create a task connected to the work.','quick',['Add task','New task']],['New project','project','Start a new project record.','quick',['New project','Add project']]]},
    money:{label:'Money',icon:'money',aliases:['money','finance','finances'],actions:[['Overview','chart','Return to the financial overview.','tab',['Overview','Dashboard']],['Transactions','list','Review income and expense activity.','tab',['Transactions','Activity']],['Recurring','repeat','Manage repeating commitments.','tab',['Recurring','Commitments']],['Cash calendar','calendar','Open the cash-flow calendar.','tab',['Cash calendar','Calendar','Cash flow']],['Ledger','ledger','Open the bookkeeper-style ledger.','tab',['Ledger','Bookkeeper’s Ledger','Bookkeepers Ledger']],['Add income','income','Record expected or received income.','quick',['Add income','New income']],['Add expense','expense','Record an outgoing payment or bill.','quick',['Add expense','New expense']]]},
    content:{label:'Content',icon:'content',aliases:['content','social','social media'],actions:[['Calendar','calendar','Plan content by date.','tab',['Calendar','Content calendar']],['Library','list','Review drafts, ready and published content.','tab',['Library','Content library']],['Ideas','idea','Capture ideas before they disappear.','tab',['Ideas','Idea bank']],['Performance','chart','Review manually entered results.','tab',['Performance','Analytics']],['New content','content','Create and schedule a new post.','quick',['New content','Add content','New post']],['Quick idea','idea','Capture a content idea quickly.','quick',['Quick idea','Add idea','New idea']]]},
    growth:{label:'Growth',icon:'growth',aliases:['growth','goals'],actions:[['Goals','goal','Review business, financial and personal goals.','tab',['Goals']],['Habits','habit','Track the routines supporting your week.','tab',['Habits','Habit tracker']],['Monthly reset','reset','Review wins, lessons and next-month focus.','tab',['Monthly reset','Reset','Monthly review']],['Add goal','goal','Create a new goal and next milestone.','quick',['Add goal','New goal']],['Add habit','habit','Create a habit to track.','quick',['Add habit','New habit']]]},
    notes:{label:'Notes',icon:'notes',aliases:['notes','journal'],actions:[['Brain dump','note','Open a blank space for unfiltered thoughts.','tab',['Brain dump']],['Quick notes','notes','Review short saved notes.','tab',['Quick notes','Notes']],['Journal','note','Open dated journal entries.','tab',['Journal']],['Meetings','client','Review meeting minutes and follow-ups.','tab',['Meetings','Meeting minutes']],['New entry','note','Create a new note or journal entry.','quick',['New entry','Add note','New note','Journal entry']]]}
  };
  let currentArea='home',pendingHighlight=null,toastTimer=null;
  const normalize=v=>String(v||'').replace(/[+→›⌄]/g,' ').replace(/\s+/g,' ').trim().toLowerCase();
  const isOurUI=el=>!!el.closest(UI_SELECTOR);
  const visible=el=>!!(el&&(el.offsetWidth||el.offsetHeight||el.getClientRects().length));
  function findOriginalNavigation(){const labels=['home','plan','work','money','content','growth','notes'];const candidates=[...document.querySelectorAll('nav,header,[class*="nav"],[class*="menu"]')].filter(el=>!isOurUI(el));let best=null,bestScore=0;candidates.forEach(el=>{const txt=normalize(el.innerText);const score=labels.filter(label=>txt.includes(label)).length;if(score>bestScore&&score>=4){best=el;bestScore=score;}});if(best)best.classList.add('lceo-original-main-nav');return best;}
  function allClickables(){return [...document.querySelectorAll('button,a,[role="button"],[tabindex]')].filter(el=>!isOurUI(el));}
  function findClickable(labels,{preferVisible=true}={}){const wanted=labels.map(normalize);const list=allClickables();const exact=list.filter(el=>wanted.includes(normalize(el.innerText||el.getAttribute('aria-label')||el.title)));const partial=list.filter(el=>wanted.some(w=>normalize(el.innerText||el.getAttribute('aria-label')||el.title).includes(w)));const candidates=[...exact,...partial.filter(x=>!exact.includes(x))];return candidates.find(el=>!preferVisible||visible(el))||candidates[0]||null;}
  function areaFromElement(el){const raw=normalize(el?.innerText||el?.getAttribute('aria-label')||el?.dataset?.page||el?.dataset?.area||'');for(const key of AREA_ORDER){if(areas[key].aliases.some(a=>raw===a||raw.includes(a)))return key;}return null;}
  function navigateArea(key){currentArea=key;updateActiveArea();renderActionRail();const cfg=areas[key];const selectors=[`[data-page="${key}"]`,`[data-area="${key}"]`,`[data-section="${key}"]`,`[data-view="${key}"]`];let target=selectors.map(s=>document.querySelector(s)).find(el=>el&&!isOurUI(el));if(!target)target=findClickable(cfg.aliases,{preferVisible:false});if(target){target.click();setTimeout(()=>{detectArea();renderActionRail();},180);}else showToast(`${cfg.label} is not connected yet.`);}
  function detectArea(){const nav=document.querySelector('.lceo-original-main-nav');const active=nav?.querySelector('.active,[aria-current="page"],[aria-selected="true"]');const found=areaFromElement(active);if(found&&found!==currentArea){currentArea=found;updateActiveArea();renderActionRail();return;}const heading=[...document.querySelectorAll('main h1,main h2,[class*="page"] h1,[class*="page"] h2')].find(el=>!isOurUI(el)&&visible(el));const fromHeading=areaFromElement(heading);if(fromHeading&&fromHeading!==currentArea){currentArea=fromHeading;updateActiveArea();renderActionRail();}}
  function updateActiveArea(){document.querySelectorAll('.lceo-left-button').forEach(btn=>btn.classList.toggle('active',btn.dataset.area===currentArea));}
  function createLeftRail(){const rail=document.createElement('aside');rail.id='lceoLeftRail';rail.className='lceo-left-rail';rail.innerHTML=`<div class="lceo-left-brand"><div class="lceo-left-mark">J</div><div class="lceo-left-brand-copy"><strong>Life & CEO OS</strong><small>Jess workspace</small></div></div><nav class="lceo-left-menu">${AREA_ORDER.map(key=>`<button class="lceo-left-button" type="button" data-area="${key}"><span class="lceo-left-icon">${svg[areas[key].icon]}</span><span class="lceo-left-label">${areas[key].label}</span></button>`).join('')}</nav><div class="lceo-left-footer"><button class="lceo-nav-mode-button" type="button" id="lceoNavMode"><span class="lceo-left-icon" id="lceoNavModeIcon"></span><span class="lceo-nav-mode-copy" id="lceoNavModeCopy"></span></button></div>`;document.body.appendChild(rail);rail.querySelectorAll('[data-area]').forEach(btn=>btn.addEventListener('click',()=>navigateArea(btn.dataset.area)));rail.querySelector('#lceoNavMode').addEventListener('click',toggleNavMode);}
  function createRightUI(){const rail=document.createElement('aside');rail.id='lceoActionRail';rail.className='lceo-action-rail';rail.innerHTML='<div class="lceo-action-brand" id="lceoActionBrand">HOME</div><div class="lceo-action-list" id="lceoActionList"></div><button class="lceo-action-open" id="lceoActionOpen" type="button" data-tooltip="Open Action Menu"><span class="lceo-action-icon">'+svg.menu+'</span></button>';const backdrop=document.createElement('div');backdrop.id='lceoActionBackdrop';backdrop.className='lceo-action-backdrop';const drawer=document.createElement('aside');drawer.id='lceoActionDrawer';drawer.className='lceo-action-drawer';drawer.setAttribute('aria-hidden','true');drawer.innerHTML='<header class="lceo-drawer-header"><div class="lceo-drawer-header-top"><div><span class="lceo-drawer-kicker">Action Menu</span><h2 class="lceo-drawer-title" id="lceoDrawerTitle">Home actions</h2><p class="lceo-drawer-subtitle" id="lceoDrawerSubtitle">Work with this page without losing your place.</p></div><button class="lceo-drawer-close" id="lceoDrawerClose" type="button" aria-label="Close Action Menu">×</button></div></header><div class="lceo-drawer-body"><button class="lceo-drawer-primary" id="lceoUniversalAdd" type="button">＋ Open universal Add menu</button><div class="lceo-drawer-section-title">Available on this page</div><div class="lceo-drawer-actions" id="lceoDrawerActions"></div></div>';const toast=document.createElement('div');toast.id='lceoNavToast';toast.className='lceo-nav-toast';document.body.append(backdrop,drawer,rail,toast);rail.querySelector('#lceoActionOpen').addEventListener('click',()=>openDrawer());drawer.querySelector('#lceoDrawerClose').addEventListener('click',closeDrawer);backdrop.addEventListener('click',closeDrawer);drawer.querySelector('#lceoUniversalAdd').addEventListener('click',()=>openUniversalAdd());}
  function renderActionRail(){const cfg=areas[currentArea]||areas.home;const brand=document.querySelector('#lceoActionBrand');if(!brand)return;brand.textContent=cfg.label.slice(0,4).toUpperCase();const list=document.querySelector('#lceoActionList');list.innerHTML=cfg.actions.slice(0,7).map((a,i)=>`<button class="lceo-action-button" type="button" data-action-index="${i}" data-tooltip="${a[0]}"><span class="lceo-action-icon">${svg[a[1]]||svg.plus}</span></button>`).join('');list.querySelectorAll('[data-action-index]').forEach(btn=>btn.addEventListener('click',()=>openDrawer(Number(btn.dataset.actionIndex))));document.querySelector('#lceoDrawerTitle').textContent=`${cfg.label} actions`;document.querySelector('#lceoDrawerSubtitle').textContent=`Tools and shortcuts connected directly to ${cfg.label}.`;const actions=document.querySelector('#lceoDrawerActions');actions.innerHTML=cfg.actions.map((a,i)=>`<button class="lceo-drawer-action ${pendingHighlight===i?'highlighted':''}" type="button" data-drawer-index="${i}"><span class="lceo-drawer-action-icon">${svg[a[1]]||svg.plus}</span><span class="lceo-drawer-action-copy"><strong>${a[0]}</strong><small>${a[2]}</small></span><span class="lceo-drawer-action-arrow">›</span></button>`).join('');actions.querySelectorAll('[data-drawer-index]').forEach(btn=>btn.addEventListener('click',()=>executeAction(cfg.actions[Number(btn.dataset.drawerIndex)])));}
  function openDrawer(index=null){pendingHighlight=index;renderActionRail();document.querySelector('#lceoActionDrawer').classList.add('open');document.querySelector('#lceoActionBackdrop').classList.add('open');document.querySelector('#lceoActionDrawer').setAttribute('aria-hidden','false');if(index!==null)setTimeout(()=>document.querySelector(`[data-drawer-index="${index}"]`)?.scrollIntoView({block:'center',behavior:'smooth'}),80);}
  function closeDrawer(){pendingHighlight=null;document.querySelector('#lceoActionDrawer')?.classList.remove('open');document.querySelector('#lceoActionBackdrop')?.classList.remove('open');document.querySelector('#lceoActionDrawer')?.setAttribute('aria-hidden','true');}
  function executeAction(action){const[label,icon,desc,type,candidates]=action;if(type==='tab'){const target=findClickable(candidates);if(target){target.click();showToast(`${label} opened.`);closeDrawer();}else showToast(`${label} will be connected as this page is refined.`);return;}if(type==='quick'){openQuickAction(candidates,label);return;}}
  function openUniversalAdd(){const add=findClickable(['+ Add','Add','Quick Add','Create']);if(add){add.click();closeDrawer();}else showToast('The universal Add menu could not be found on this screen.');}
  function openQuickAction(candidates,label){let direct=findClickable(candidates);if(direct){direct.click();closeDrawer();return;}const add=findClickable(['+ Add','Add','Quick Add','Create']);if(!add){showToast(`${label} is not connected on this screen yet.`);return;}add.click();setTimeout(()=>{direct=findClickable(candidates);if(direct){direct.click();closeDrawer();}else showToast(`Open the Add menu and choose “${label}”.`);},160);}
  function navMode(){return localStorage.getItem('life-ceo-os-left-nav-mode')||'full';}
  function applyNavMode(){const compact=navMode()==='compact';document.body.classList.toggle('lceo-nav-compact',compact);document.querySelector('#lceoNavModeIcon').innerHTML=compact?svg.expand:svg.collapse;document.querySelector('#lceoNavModeCopy').textContent=compact?'Expand menu':'Condense menu';}
  function toggleNavMode(){localStorage.setItem('life-ceo-os-left-nav-mode',navMode()==='compact'?'full':'compact');applyNavMode();}
  function showToast(msg){const t=document.querySelector('#lceoNavToast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2600);}
  function init(){if(document.querySelector('#lceoLeftRail'))return;findOriginalNavigation();createLeftRail();createRightUI();document.body.classList.add('lceo-nav-ready');applyNavMode();const initial=document.querySelector('.lceo-original-main-nav .active,.lceo-original-main-nav [aria-current="page"]');currentArea=areaFromElement(initial)||'home';updateActiveArea();renderActionRail();const observer=new MutationObserver(()=>{findOriginalNavigation();detectArea();});observer.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class','aria-current','aria-selected']});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer();});document.addEventListener('click',e=>{if(!isOurUI(e.target))setTimeout(detectArea,80);},true);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,60));else setTimeout(init,60);
})();